### ISSUE TITLE
Make the overlay ignore fullscreen

### ISSUE THREAD

**Issue by m0rtis0** [trigg/Discover#107]
Hello,
is it possible to show the overlay even in fullscreen mode?
In dwm this does not work, the window in fullscreen overlaps the overlay

Thanks,
m0rtis0

**Comment by trigg** [comment]
This is how it should work. I'm uncertain of dwm but I'd assume it's either a config option in that or whatever compositor you might be using.

**Comment by Sukid** [comment]
It might just be an issue in tiling WMs? Because I'm having the same problem in Sway. If I fullscreen the game container the overlay disappears.
I've researched it and there's no setting in the config file to let it render on the "overlay" layer, but there is a way to add that functionality to the application itself. That might just be with sway/wlroots however, can't say the same for dwm necessarily.

**Comment by Sukid** [comment]
This reddit thread has an example of a patch to make wofi render on the "overlay" layer of Sway, maybe this might be of some use to you?
https://www.reddit.com/r/swaywm/comments/hyti1v/wofi_appears_under_full_screen_windows/
