### ISSUE TITLE
Does not start on MacOS

### ISSUE THREAD

**Issue by AmonWarner** [trigg/Discover#110]
So I tried installing this. everything ran smoothly until I ran it and got that error and nothing else. I am on the latest version of macos Catalina and on python 3.7, I also tried reinstalling, what happened?

**Comment by MurdoMaclachlan** [comment]
Does macOS Catalina include X11? It seems that the problem is as a result of these lines:

```
if not self.get_display().supports_input_shapes():
        logging.info(
            "Input shapes not available. Quitting")
```

It looks like supports_input_shapes() is returning false, which suggests input_shape_combine_mask() is failing. It might be that the window system for macOS Catalina doesn't support input shapes.

From a few searches, GDK documentation mentions that windows doesn't support them, and that X11 requires version 1.1 to support them, but it doesn't make any mention of macOS of any kind.

> On the X11 platform, this requires version 1.1 of the shape extension.
> On the Win32 platform, this functionality is not present and the function does nothing.

Need confirmation from trigg on that, though, I haven't used GDK much. Most of this is based on some searches engine results.

**Comment by trigg** [comment]
@MurdoMaclachlan hit the nail on the head. Zero effort has been expended to test and debug MacOS simply because I haven't got the hardware, software or inclination to get either.

This doesn't mean for certain it can't be made to work but it would require a lot of testing to make something workable. We require a specific set of quirks in X to work on X and a specific library to work on Wayland so I wouldn't want to bet we could patch it without a test machine.

For starters, if you feel like you want to try editing the code and testing it the obvious first step is find the error above and just remove the exit command and see how it handles.

discover_overlay/overlay.py  Line 69
Just remove the line and see how well it plays

**Comment by trigg** [comment]
I should probably add as a follow up. The most likely thing to happen is you won't be able to click on anything under the overlay.

**Comment by AmonWarner** [comment]
Thanks! I'll take a look and update you.

**Comment by jasikpark** [comment]
I would love for this support!

**Comment by trigg** [comment]
Unfortunately I don't have time or expertise for this, and I believe the correct way for Mac would be to use a Mac specific GUI library instead of GTK.
 
Anyone interested in forking the project and making a go at Mac port is allowed to message me on this bug and I'll help them where I can with it.
