### ISSUE TITLE
Desktop icon looks ugly when enlarged

### ISSUE THREAD

**Issue by mavit** [trigg/Discover#139]
Image `discover-overlay.png` is currently 32×32 pixels, which means it looks pretty bad when scaled up to appear in e.g., the Gnome applications menu.  Could a larger image be provided instead?

**Comment by trigg** [comment]
I was secretly hoping I'd have annoyed @midget3111 into remaking the icons for me by making something so awful he had to take action.

Apparently I underestimated his patience.

**Comment by midget3111** [comment]
![discover-overlay](https://user-images.githubusercontent.com/964775/113458695-0a1a9f00-940b-11eb-8c96-1e7e3269fff4.png)

**Comment by midget3111** [comment]
Yes, I did just download GIMP especially. 
I'll have a think about an alternate logo.

**Comment by NicolaSmaniotto** [comment]
![discover-overlay](https://user-images.githubusercontent.com/22083075/149567856-e01a763e-5fed-4e1c-a3d0-962e60cda210.png)

What about something like this? It's actually an svg, but github does not allow that upload. The scaling problem could be fixed by using the vector image itself, as it is supported by the desktop file specification.

In my opinion this looks pretty good, even when scaled down, but I'm not convinced by the empty "name tags".
Also, I fear the discord logo cannot be used, so maybe a generic stylized portrait?

This is how it would appear in the KDE Plasma application list:

![Screenshot_20220114_194639](https://user-images.githubusercontent.com/22083075/149568779-13122211-0fd5-46c0-a82c-ed77ecac987b.png)

![Screenshot_20220114_194737](https://user-images.githubusercontent.com/22083075/149568842-34cd8999-8eba-4f8c-af0d-50ea5e51c847.png)

**Comment by trigg** [comment]
The problem here is that it is using the trademark/copyrighted logo. I don't want the hassle of lawsuits so we'll need something that isn't their IP

**Comment by NicolaSmaniotto** [comment]
As I thought, here is the "generic stylized portrait" alternative:
![discover-overlay](https://user-images.githubusercontent.com/22083075/149588462-285be93f-b8ed-4c77-8b6e-557d8cfabe8c.png)

**Comment by midget3111** [comment]
Ohhh. Now we're talking. I like this idea.

**Comment by trigg** [comment]
I agree, good plan. Thank you and I'll commit this tomorrow

**Comment by NicolaSmaniotto** [comment]
I'll open a PR with the scalable svg and different png sizes as a fallback

**Comment by trigg** [comment]
Thank you for the contribution!

**Comment by NicolaSmaniotto** [comment]
You are welcome.

I tried keeping the svg as clean as possible, in case someone whishes to edit it. There are different named layers and everything has a size that is an integer amount of pixels (often powers of 2).

**Comment by trigg** [comment]
This is the level of detail I love. I did eye over the SVG contents and was very happy with it
