### ISSUE TITLE
[Feature] Ripcord Support

### ISSUE THREAD

**Issue by jeffboy70** [trigg/Discover#196]
Lots of people use ripcord because it's way faster than the standard discord client, but I'd really like to have overlay support with it.

**Comment by trigg** [comment]
Due to the way discord streamkit works I'd be loathe to add support to this project for ripcord, as either ripcord would need to open another port and emulate the API or for this project to support a whole new protocol shared with ripcord.

I'm closing this, but I believe this is request should either go to ripcord as they could write a first-party overlay into it, or to write a from-scratch overlay with a new shared API with ripcord.
