### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by midget3111** [trigg/Discover#2]
When the settings window is open, it has no icon in the system tray

**Comment by midget3111** [comment]
This is still outstanding, as it's aesthetic I'm marking it as a 0.2 goal.

**Comment by i-need-to-tell-you-something** [comment]
For me it does have an icon in the system tray. So I'm guessing you mean that the window itself is lacking an icon - which is expressed by lack of an icon (or an OS placeholder icon) in e.g.:
* The window's titlebar
* Desktop environment's taskbar aka task manager aka window list
* Alt+Tab menu

**Comment by Findus23** [comment]
For me (KDE Plasma), discover-overlay does not display a tray icon (unlike discord-overlay which did).

I am assuming this is because of 
https://github.com/trigg/Discover/blob/62aa3a7da69fa5cb17918debf3ff7090c48b0da6/discover_overlay/discover_overlay.py#L1647-L1663

`from gi.repository import AppIndicator3` does not work for me, it throws:
> <stdin>:1: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.

and the except loads an icon that is not in the system theme (I think).

Interestingly adding `gi.require_version('AppIndicator3', '0.1')` removes the warning, but does not solve the issue. So it might be in the part that registers the discover.png as the icon to use for "discover". (maybe because I installed it in a virtualenv and therefore it doesn't check the share/icons/ path)

**Comment by i-need-to-tell-you-something** [comment]
@Findus23 Interestingly it worked fine for me IIRC on KDE Plasma on Kubuntu 18.04 and Kubuntu 16.04.
