### ISSUE TITLE
Using discover overlay causes system notifications to break

### ISSUE THREAD

**Issue by DO-Ui** [trigg/Discover#242]
**Steps to Reproduce**
1. Run discover overlay with a Floating overlay location
2. Try and use `notify-send` while in a voice channel and send a notification

**Expected behavior**
System notification should show up

**Problematic behavior**
Notification does not show up and does not appear in notification logs

**Desktop (please complete the following information):**
 - OS: Pop_OS! 22.04

**Installation Method**
Pypi with pip

**Additional context**
Its a small issue but very odd nonetheless

**Comment by trigg** [comment]
What desktop environment is Pop OS?

**Comment by MurdoMaclachlan** [comment]
Interesting, I have an issue that might be related. Been having a problem for a while were my Python scripts crash as soon as they try to display a desktop notification.

The difference is, my notifications do actually display, and the programs crash right after, so I was just wrapping them in try-excepts and ignoring it. Never considered that Discover might be causing the problem since I forget it's running when I'm not using Discord, but on testing it only happens when Discover's open.

Here's the output from one of my crashed scripts, if it helps:

![image](https://user-images.githubusercontent.com/47920497/167293198-180745d0-254d-482c-a579-d931cd4da5ab.png)

For OS & DE, I'm using Xfce on Slackware Current.

**Comment by trigg** [comment]
That sounds very likely related. Between this and #239 I might drop dbus and fall back to Discord-only notifications.

**Comment by DO-Ui** [comment]
> What desktop environment is Pop OS?

I'm using Gnome 42 as the desktop environment
