### ISSUE TITLE
No system tray icon on Plasma Wayland

### ISSUE THREAD

**Issue by Victor239** [trigg/Discover#255]
**Steps to Reproduce**
1. Run Discover

**Expected behavior**
Discover should have a system tray icon, like it does on X11.

**Problematic behavior**
No system tray icon appears. Joining any voice channel will still show the overlay however.

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04

**Installation Method**
 - Flatpak (Flathub)

**Additional context**
N/A

**Comment by alsoGAMER** [comment]
> This is specific to the flathub version on wayland

This also happens when using the system package manager, it isn't a flatpak specific issue nor a wlroots one.
With this being written with GTK, you can check the implementation used [here](https://github.com/z411/trackma/blob/master/trackma/ui/gtk/application.py) to figure out why it isn't working properly.
