### ISSUE TITLE
Incorrect hide/display policies

### ISSUE THREAD

**Issue by ng8weji9vowdv** [trigg/Discover#333]

**Comment by midget3111** [comment]
What is this an issue for exactly?

Issue templates are there for a reason, please use them!

**Comment by iiscosd3** [comment]
So, basically. We have mouseover.
https://github.com/trigg/Discover/blob/a466a7be5b679e53fd27be3d5de7a5984dcded8c/discover_overlay/overlay.py#L459-L462

which sets draw_blank, and calls set_needs_redraw.
https://github.com/trigg/Discover/blob/a466a7be5b679e53fd27be3d5de7a5984dcded8c/discover_overlay/overlay.py#L189-L196

But we also have this and it sets the entire frame as untouchable, which kind of makes sense, right?

But, what is going to happen once the thing fades out? Its going to trigger mouseout, since the frame isn't solid anymore, and it will trigger the timeout thing (which is already a bug since the actual timeout is fadeout on mousever + timeout).

https://github.com/trigg/Discover/blob/a466a7be5b679e53fd27be3d5de7a5984dcded8c/discover_overlay/overlay.py#L464-L471


Which will trigger flashing and redraw...

We cannot get rid of set_untouchable since we do not really have an actual frame we can rely on, but multiple, so once we click on it it will misbehave.

Need a new strategy where mouseover will remain as is, at the same time the object will not be touchable, but, also remain inthe mouse over sttate. In any other framework i would've used raw events and rely on them, covering the usecase. But here, idk.

**Comment by iiscosd3** [comment]
We need to set it invisible and pass all clicks through it, down to the layers under it? I guess that's the only way, am not sure.

**Comment by trigg** [comment]
Unless I've vastly misunderstood the underlying technologies, we quickly run into the issue of wanting a state that doesn't exist.

The state where we get alerted to mouse move/mouse click/mouse in/mouse out will also consume those events. I don't see any way to monitor the events and still allow the application below them to see them.

Mouse out events trigger the moment something causes the mouse to be outside the window, which as you say happens as soon as we set window as untouchable. If we simply drew blank and kept the previous mask we'd consume pointer events, only allowing user to see through but not click.

**Comment by iiscosd3** [comment]
> we simply drew blank and kept the previous mask we'd consume pointer events, only allowing user to see through but not click.

```
        
    self.connect("button-press-event", self.on_button_pressed)

    def on_button_pressed(self, btn, event):
        return False
```

basically something like could've fixed that issue.

**Comment by trigg** [comment]
Did you test this? This changes nothing on my setup.

The event continues on in GTK, gets to the end, but is still consumed in window-manager context and doesn't continue out to the next window.

**Comment by iiscosd3** [comment]
> Did you test this? This changes nothing on my setup.
> 
> The event continues on in GTK, gets to the end, but is still consumed in window-manager context and doesn't continue out to the next window.

i checked on regular clicks and yes it did work with a couple changes ive mentioned above, it was just a complex solution but i deleted it because overlay kept bugging lol
